##https://notes.kodekloud.com/docs/GitHub-Actions-Certification/Custom-Actions/Metadata-syntax-for-GitHub-Actions
## https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: "Get & cache Dependencies"
description: "Get code and cache dependencies (via npm) and cache them for future runs"
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4 ## we can use actions which are precreated here || https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
